name: "Destroying Resources"

on:
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Destroy all resources'
        required: true

env:
  region: ap-south-1
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        

      - name: Initialize Terraform
        
        run: terraform init
        
      - name: Terraform Plan Destroy
        
        run: terraform plan  -destroy  -out=tfplan
        
        
      - name: Destroy Resources
        
        run: terraform destroy   -auto-approve 
